travis:
  secure:
    BINSTAR_TOKEN: Zsi44rlonCTRDPmX4IcCpTHsJZ2xH0ghyWs2YPafyeEVbL4RSilxAI7gmvY5q1W+TwS19TmxKVsM3/kJjyBCN4FYOUFp+qkut+YIeUzkLXGtoRHE7fqY66okrFFiDpBnp5VrpeIxj14qZfKTyXfr6I2qSMQW3cI449I3jRzi98hG7gnSgzWxTnVmelnRkGVHzz+eGgROowM95TqAaTJTp4VUKFYtcghfTjAY5DE9QMgBX5JMVUFrIsLf7i0txivl9KilrMa2KyRc3XjFVx+Wiv/1qR+QsWfXz9F3lrknGnIbURy+sBDq/RhcSDS+LIrIU/NcA6P7L+Gcmjz/k4o5FqcYCd3blMNVTrrvYEFvbsPJaH/KLMpn5wsDsoRjowXPXunb/+FvmawfqCkZHcjOsn24RbTwk2AeyCiU/pYfJk5SBhnOfDiJsny6Ftq+ZHKO63QwaoBUhfDCBWAiZP9phoJV/oQ3t8M6A9otdwvCgK2yCFwQ3TtxxeHkjb3C+kuV1WgXwYRFgM2hO3MlUiTZkQS7h9YJj7MFDK1iv1mF7xgxjHuUZAfaQk6itkH0x0pkDBOhXVpcmHBVTw/+ZWdltTw2T8o+xMH/hlIY5YDXLRS1lN4xQatif19Ue6AUaxzoER/TgkCafuoisChgmHRDwPzMmbYDfFaBMQAO4MB0o3M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
